version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    working_directory: ~/supermarket
    docker:
      - image: circleci/ruby:2.6.5-stretch-node
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:10-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: supermarket_test
    executor: ruby/default
    steps:
      - checkout
      - run:
          command: mkdir -p /tmp/test-results
      - run:
          name: Install bundler
          command: gem install bundler
      - ruby/bundle-install

      - run:
          name: Database Setup
          command: |
            bundle exec rake db:schema:load

      - run:
          name: Run unit tests
          command: |
            bundle exec rspec

      # Save artifacts
      - store_test_results:
          path: /tmp/test-results
